#GAME FRAMERATE
FPS = 60
#GAME WINDOW WIDTH AND HEIGHT
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 800
#GAME WINDOW CENTER VALUES
CENTER_W, CENTER_H = SCREEN_WIDTH/2, SCREEN_HEIGHT/2

#FONT SIZES IN PIXELS
BIG_FONTSIZE = 60
FONTSIZE = 30
#COLORS
BLACK = (0,0,0)
WHITE = (255,255,255)
RED = (255,0,0)
DARK_RED = (100,0,0)
GREEN = (0,150,0)
DARK_GREEN = (13,110,13)
BLUE = (0,0,255)
NORMAL_GRAY = (127.5, 127.5, 127.5)

#SIZE OF BUTTONS
BUTTON_WIDTH = 500
BUTTON_HEIGHT = 100

#SIZE OF IMAGES
IMAGE_WIDTH = 400
IMAGE_HEIGHT = 200

#SIZE OF SHAPES
SHAPE_WIDTH = 300
SHAPE_HEIGHT = 100

#SIZE OF SLIDERS
SLIDER_WIDTH = 500
SLIDER_HEIGHT = 50

#BACKGROUND COLORS OF BUTTONS
BG = DARK_GREEN
BG_HOV = GREEN
BG_PRE = RED

#FOREGROUND COLORS OF BUTTONS
FG = BLACK
FG_HOV = BLACK
FG_PRE = DARK_RED

#DIFFERENT SHAPES
RECT = "rect"
CIRCLE = "circle"

#MENU BUTTTONS TEXTS
MENU_BTNS = ["CHANGE TEXT"]

#MENU BUTTONS DEBUGS
MENU_DEBUGS = ["CHANGE TEXT"]

#TEXT OF A TEXT ELEMENT
TEXT = "CHANGE ME"

#CHANGED TEXT OF A TEXT ELEMENT
CHANGE = "LOL"

#IMAGES PATH
PATH = "img/"

#IMAGE NAME
IMAGE1 = "image.png"

#MIN AND MAX VALUES OF SLIDER
MIN = 0
MAX = 10

#CURRENT VALUE OF SLIDER
VAL = 0.0